apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: calico-node
      spec:
        template:
          spec:
            containers:
              - name: kicker
                image: ghcr.io/tkhq/calico-kicker
                command:
                  - /calico-kicker
                env:
                  - name: POD_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.name
resources:
  - role:pod-killer.yaml
images:
  - name: ghcr.io/tkhq/calico-kicker
    newTag: v0.0.1@sha256:f5451d2c0fa88354a64738094a849ead10eec149ed43dc76fa45bf01386a3990
