kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-killer
rules:
  # Used for creating service account tokens to be used by the CNI plugin
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-killer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-killer
subjects:
  - kind: ServiceAccount
    name: calico-node
